### ISSUE TITLE
[Bug] index out of bounds

### ISSUE THREAD

**Issue by sjy1203** [thaihungle/DMNC#1]
Hi, great paper in KDD2018 and wonderful idea to utilize Dual Control DNC in healthcare. I found the code link in your paper  and want to see the model effect in drug prediction. 

So I extract data from MIMIC-III and transform the data form as introduced in readme.md as follows:
> patient_records.shape = (patient_idx, 3, codes)
 three word2idx and idx2word dict

But when I run the code below:
`train DMNC_l>>python3 emr_run.py --mode=train --use_mem=True --share_mem=False`
I get some erros:
> Traceback (most recent call last):
  File "emr_run.py", line 677, in <module>
    mimic_task_persit_real_dual(args)
  File "emr_run.py", line 464, in mimic_task_persit_real_dual
    output_size, ii,multi=multi)
  File "emr_run.py", line 220, in prepare_mimic_sample_dual_persist
    word_space_size_output, 0,multi=multi))
  File "emr_run.py", line 178, in prepare_mimic_sample_dual
    input_vec2 = np.array([onehot(code, word_space_size_input2) for code in input_vec2])
  File "emr_run.py", line 178, in <listcomp>
    input_vec2 = np.array([onehot(code, word_space_size_input2) for code in input_vec2])
  File "emr_run.py", line 123, in onehot
    vec[int(index)] = 1.0
IndexError: index 3312 is out of bounds for axis 0 with size 1422

I have already found some code error like:
https://github.com/thaihungle/DMNC/blob/748d9998bc9b9fd06da13ad0bf88c184cdac24d4/dual_task/emr_run.py#L260
I speculate the input_size1 is the unique number of diagnoses, and input_size2 is the unique number of procudures, and output_size for drugs. But same bug remains when I fixed the above code.

Could you please update the code when you're free, thanks a lot~

**Comment by sjy1203** [comment]
I found that you used 0 as a separator 
https://github.com/thaihungle/DMNC/blob/748d9998bc9b9fd06da13ad0bf88c184cdac24d4/dual_task/emr_run.py#L218
but there may be 0 in both input_seq and input_seq2 which caused the index out of bounds error.
I think you should mention 0 shouldn't be word_idx in token2str and str2token dict in your readme file.

**Comment by thaihungle** [comment]
Thank you for your interest in my paper. First, the meaning of the variable names such as *diag, *drug and *proc may change dependent on your inputs and output choice. In my paper, the output is drug; and the inputs are diagnoses/procedures so it’s confusing.  Sorry about that, I should have used better variable names.  Second, it is true that I spare token 0 and 1 for special purposes so please index your medical code from 2. Third, it seems that the error is due to some conflicts in your data preparation. The input 2’s number of code is only 1422 while in the sequence there is an index of value 3312. Please check the code from line 209 to 220 carefully. Maybe there is something wrong with the order in variable adm.
